#!/usr/bin/env ruby

require "simple_mailing_list"
require "daemons"

options = {
  ARGV: ARGV,
  dir_mode: :normal,
  dir: Dir.pwd,
  log_output: true
}

File.write("daemons_simple_mailing_list.rb", <<EOS
Dir.chdir(File.dirname(File.expand_path(__FILE__)))
SimpleMailingList::CLI.start(ARGV)
EOS
)

ARGV.push( "--", "loop_main_jobs" ) unless ARGV.index("--")
Daemons.run("daemons_simple_mailing_list.rb", options)
