#!/usr/bin/env ruby

require "simple_mailing_list"
require "daemons"

options = {
  dir_mode: :normal,
  dir: Dir.pwd,
  log_output: true
}

Daemons.run_proc("daemons_simple_mailinglist", options) do
  Dir.chdir(options[:dir])
  ARGV.push( "--", "loop_main_jobs" ) unless ARGV.index("--")
  until ARGV.shift == "--"
    break if ARGV.empty?
  end
  SimpleMailingList::CLI.start(ARGV)
end
